/*  oaa-next -- the agent library
 *
 *  Provenance: RECONSTRUCTED.
 *  Developer's Guide v2.3.2 sections 4.5, 5, 6, 7 and 9.
 */

:- module(oaa_agent,
          [ oaa_connect/2,              % +Params, -Address
            oaa_register/4,             % +ConnId, +Name, +Solvables, +Params
            oaa_declare/2,              % +Solvables, +Params
            oaa_undeclare/2,            % +Solvables, +Params
            oaa_redeclare/3,            % +Solvable, +NewSolvable, +Params
            oaa_solvables/1,            % -Solvables

            oaa_solve/1,                % +Goal
            oaa_solve/2,                % +Goal, +Params
            oaa_solve_local/2,          % +Goal, +Params

            oaa_add_data/2,             % +Clause, +Params
            oaa_remove_data/2,          % +Clause, +Params
            oaa_replace_data/3,         % +Clause1, +Clause2, +Params

            oaa_name/1,                 % -Name
            oaa_local_id/1,             % -LocalId
            oaa_primary_address/1,      % -Address
            oaa_address/3,              % ?ConnId, ?Kind, ?Address

            oaa_handle_event/2,         % +ConnId, +Event
            oaa_agent_reset/0,
            oaa_next_goal_id/1          % -GoalId
          ]).

:- use_module('../icl/icl_term').
:- use_module('../icl/icl_params').
:- use_module('../runtime/com_tcp').
:- use_module('../runtime/oaa_event').
:- use_module(oaa_solvable).
:- use_module(oaa_data).
:- use_module(oaa_trigger).

/** <module> The OAA agent library

What it means to be an OAA agent.  The Developer's Guide puts it that the
capabilities provided by the agent library determine what an OAA agent is, and
this module is that: connect, register, declare solvables, request services,
answer requests, maintain data, disconnect.

The Facilitator uses this same library.  That is not an economy; it is the
architecture.  A facilitator is an ordinary agent that happens to declare the
facilitator solvables, which is exactly why a facilitator can be a client of
another facilitator with no separate federation protocol.
*/

:- dynamic my_name/1.
:- dynamic my_local_id/1.
:- dynamic my_solvable/1.
:- dynamic goal_counter/1.
:- dynamic parent_conn/1.

%   Goal IDs are generated by agent library code.  From OAA 2.3.2 they start
%   from a random integer rather than from 1, because sequential ids let the
%   replies to two different solve requests be intermixed.  The same reasoning
%   requires them to stay unique across a reconnect, so the counter is seeded
%   once and never reset by connection state.

init_goal_counter :-
    (   goal_counter(_)
    ->  true
    ;   X is random(1 000 000 000),
        assertz(goal_counter(X))
    ).

:- init_goal_counter.

%!  oaa_next_goal_id(-GoalId) is det.

oaa_next_goal_id(Id) :-
    retract(goal_counter(N)),
    Id is N + 1,
    assertz(goal_counter(Id)).

oaa_agent_reset :-
    retractall(my_name(_)),
    retractall(my_local_id(_)),
    retractall(my_solvable(_)),
    retractall(parent_conn(_)),
    oaa_data_clear.

% ------------------------------------------------------------ connect

%!  oaa_connect(+Params, -Address) is det.
%
%   Open the connection to the parent facilitator.  The historical two-step is
%   com_Connect followed by oaa_Register, and it is kept: connecting and
%   registering are separate acts, because an agent may connect and only later
%   decide what it can do.

oaa_connect(Params, Address) :-
    com_connect(parent, Params, Address),
    retractall(parent_conn(_)),
    assertz(parent_conn(parent)).

%!  oaa_register(+ConnId, +Name, +Solvables, +Params) is det.
%
%   Register with the facilitator and tell it what this agent can solve.  An
%   agent with nothing to offer passes the empty list, which is explicitly
%   allowed.
%
%   The facilitator assigns the local id and passes the client's full address
%   back during this call, so registration blocks until it replies.

oaa_register(ConnId, Name, Solvables, Params) :-
    solvable_list_or_empty(Solvables, Normalized),
    retractall(my_name(_)),
    assertz(my_name(Name)),
    retractall(my_solvable(_)),
    forall(member(S, Normalized), assertz(my_solvable(S))),
    declare_builtin_solvables,
    public_solvables(Normalized, Public),
    com_send(ConnId, ev_register_solvables(Name, Public, Params)),
    (   oaa_wait_for(ev_registered(LocalId, _Address), 10, _)
    ->  retractall(my_local_id(_)),
        assertz(my_local_id(LocalId))
    ;   throw(oaa_error(registration_timeout))
    ).

%   Every agent implicitly provides oaa_trigger/5 as a data solvable, which
%   is how installed triggers become queryable through oaa_Solve like any
%   other data.  Developer's Guide 4.3.5.
%
%   It is declared private, so the facilitator is not told about it and does
%   not route other agents' trigger queries here.  The Guide does not say
%   either way; keeping it local is the conservative reading, and is noted as
%   an open question in research/implementation-notes/facilitator.md.

declare_builtin_solvables :-
    solvable_list(solvable(oaa_trigger(_T, _C, _A, _P, _I),
                           [type(data), private(true)], [write(true)]),
                  [Builtin]),
    (   my_solvable(solvable(oaa_trigger(_,_,_,_,_), _, _))
    ->  true
    ;   assertz(my_solvable(Builtin))
    ).

solvable_list_or_empty([], []) :- !.
solvable_list_or_empty(Spec, Normalized) :-
    solvable_list(Spec, Normalized).

%   A private solvable is available for local use only; the facilitator is
%   never told about it.  Developer's Guide 5.1.6.

public_solvables(All, Public) :-
    exclude(solvable_is_private, All, Public).

%!  oaa_declare(+Solvables, +Params) is det.
%!  oaa_undeclare(+Solvables, +Params) is det.
%!  oaa_redeclare(+Solvable, +NewSolvable, +Params) is det.
%
%   Modify the declared capability set after registration.  oaa_redeclare is
%   conceptually an undeclare followed by a declare, except that the two take
%   effect together -- which is what makes it the right way to change a
%   solvable's parameters or permissions.

oaa_declare(Solvables, Params) :-
    solvable_list(Solvables, Normalized),
    %  address(parent) means "declare this on the facilitator", not here: the
    %  point of a blackboard solvable is that it lives in one shared place.
    (   declares_on_parent(Params)
    ->  true
    ;   forall(member(S, Normalized), assertz(my_solvable(S)))
    ),
    public_solvables(Normalized, Public),
    (   Public == []
    ->  true
    ;   send_to_parent(ev_post_declare(add, Public, Params))
    ).

declares_on_parent(Params) :-
    icl_get_param_value(address(A), Params),
    memberchk(A, [parent, facilitator]).

oaa_undeclare(Solvables, Params) :-
    solvable_list(Solvables, Normalized),
    forall(member(solvable(G, _, _), Normalized),
           retract_solvable_matching(G)),
    public_solvables(Normalized, Public),
    (   Public == []
    ->  true
    ;   send_to_parent(ev_post_declare(remove, Public, Params))
    ).

retract_solvable_matching(Goal) :-
    (   my_solvable(solvable(G, P, Q)),
        G =@= Goal
    ->  retract(my_solvable(solvable(G, P, Q)))
    ;   true
    ).

oaa_redeclare(Old, New, Params) :-
    solvable_list(Old, [OldS]),
    solvable_list(New, [NewS]),
    OldS = solvable(OldGoal, _, _),
    retract_solvable_matching(OldGoal),
    assertz(my_solvable(NewS)),
    send_to_parent(ev_post_declare(replace, [OldS, NewS], Params)).

oaa_solvables(Solvables) :-
    findall(S, my_solvable(S), Solvables).

send_to_parent(Event) :-
    (   parent_conn(Conn)
    ->  oaa_note_event(send, Conn, Event),
        com_send(Conn, Event)
    ;   throw(oaa_error(not_connected))
    ).

%   Trigger actions are run through the callback registry rather than by
%   oaa_trigger calling this module directly, which would make the dependency
%   circular.  These two are registered once, at load time.

:- initialization(register_trigger_executors).

register_trigger_executors :-
    oaa_register_callback(trigger_solve, oaa_agent:trigger_solve_action),
    oaa_register_callback(trigger_interpret, oaa_agent:trigger_interpret_action).

trigger_solve_action(Goal, Params) :-
    ignore(oaa_solve(Goal, Params)).

%   oaa_Interpret evaluates an ICL expression.  In Phase 1 the expressions a
%   trigger action may contain are the library calls themselves, so
%   interpreting one means recognising it and performing it.
trigger_interpret_action(Goal) :-
    (   Goal = oaa_AddData(C, P)   -> ignore(oaa_add_data(C, P))
    ;   Goal = oaa_RemoveData(C, P)-> ignore(oaa_remove_data(C, P))
    ;   Goal = oaa_Solve(G, P)     -> ignore(oaa_solve(G, P))
    ;   ignore(oaa_solve(Goal, []))
    ).

% --------------------------------------------------------------- identity

oaa_name(Name) :-
    (   my_name(Name0) -> Name = Name0 ; Name = anonymous ).

oaa_local_id(Id) :-
    my_local_id(Id).

oaa_primary_address(Address) :-
    com_address(parent, Address).

oaa_address(ConnId, Kind, Address) :-
    com_connection(ConnId, Kind),
    com_address(ConnId, Address).

% ------------------------------------------------------ requesting services

%!  oaa_solve(+Goal) is nondet.
%!  oaa_solve(+Goal, +Params) is nondet.
%
%   Request a service.  With an empty parameter list this behaves like the
%   Prolog primitive call/1: it blocks until the goal is finished, it can fail
%   or succeed, and multiple solutions are obtained through backtracking.
%   That equivalence is the point of the design, and it is why the return path
%   below ends in member/2 rather than in a list.
%
%   Parameters recognised here:
%
%     * address(A)        -- bypass delegation and ask specific agents; the
%                            reserved value `self` solves locally
%     * blocking(B)       -- default true; false returns at once and the
%                            solutions arrive as an ev_solved event
%     * reply(R)          -- default true; `none` means no reply is wanted,
%                            which implies a non-blocking call
%     * solution_limit(N) -- at most N solutions from each provider
%     * provider_limit(N) -- at most N providers selected
%     * time_limit(S)     -- give up after S seconds
%     * parallel_ok(B)    -- default true
%     * reflexive(B)      -- default true; whether the requester may solve it
%     * priority(P)       -- 1..10, default 5
%     * strategy(S)       -- query, action or inform; see solve_strategy/2
%     * context(C)        -- propagated to every subsequent solve in the chain
%     * get_address(V), get_satisfiers(V), get_goal_id(V) -- return parameters

oaa_solve(Goal) :-
    oaa_solve(Goal, []).

oaa_solve(Goal, Params0) :-
    expand_strategy(Params0, Params1),
    icl_get_param_value(address(Addr), Params1, '$none'),
    (   Addr == self
    ->  oaa_solve_local(Goal, Params1)
    ;   oaa_solve_remote(Goal, Params1)
    ).

%   Strategy is shorthand for combinations of the lower-level parameters.
%   Developer's Guide 6.14.  Explicit parameters win over the macro.

expand_strategy(Params, Expanded) :-
    (   icl_get_param_value(strategy(S), Params),
        solve_strategy(S, Implied)
    ->  icl_param_apply_defaults(Implied, Params, Expanded)
    ;   icl_param_expand(Params, Expanded)
    ).

solve_strategy(query,  [parallel_ok(true)]).
solve_strategy(action, [parallel_ok(false), solution_limit(1)]).
solve_strategy(inform, [parallel_ok(true), reply(none)]).

oaa_solve_remote(Goal, Params) :-
    oaa_next_goal_id(GoalId),
    bind_return_param(get_goal_id(GoalId), Params),
    icl_get_param_value(reply(Reply), Params, true),
    icl_get_param_value(blocking(Blocking0), Params, true),
    %  reply(none) overrides blocking(true): with no reply coming, there is
    %  nothing to block on.  Developer's Guide 6.15.
    (   Reply == none -> Blocking = false ; Blocking = Blocking0 ),
    wire_params(Params, WireParams),
    send_to_parent(ev_solve(GoalId, Goal, WireParams)),
    (   Reply == none
    ->  true
    ;   Blocking == false
    ->  true
    ;   await_solutions(GoalId, Goal, Params)
    ).

%   Return parameters carry a variable that the call binds.  They are for the
%   caller and must not travel to the facilitator.

bind_return_param(Param, Params) :-
    (   icl_get_param_value(Param, Params)
    ->  true
    ;   true
    ).

wire_params(Params, WireParams) :-
    icl_param_expand(Params, Expanded),
    exclude(return_param, Expanded, WireParams).

return_param(P) :- functor(P, get_address, 1).
return_param(P) :- functor(P, get_satisfiers, 1).
return_param(P) :- functor(P, get_goal_id, 1).

await_solutions(GoalId, Goal, Params) :-
    icl_get_param_value(time_limit(Limit), Params, infinite),
    (   oaa_wait_for(ev_solved(GoalId, Requestees, Solvers, _G, _P, Solutions),
                     Limit, _)
    ->  bind_return_param(get_address(Requestees), Params),
        bind_return_param(get_satisfiers(Solvers), Params),
        member(Goal, Solutions)
    ;   %  The Developer's Guide is explicit that when a responding agent
        %  misses its time limit the facilitator causes oaa_Solve to fail --
        %  and that a late reply may still arrive afterwards, for an agent
        %  that has arranged to notice it.
        fail
    ).

%!  oaa_solve_local(+Goal, +Params) is nondet.
%
%   Solve against this agent's own solvables, without involving the
%   facilitator.  This is what address(self) selects, and it is also how the
%   agent answers requests delegated to it.

oaa_solve_local(Goal, Params) :-
    findall(Solution, local_solution(Goal, Params, Solution), Solutions0),
    apply_solution_limit(Solutions0, Params, Solutions),
    member(Goal, Solutions).

local_solution(Goal, Params, Solution) :-
    my_solvable(S),
    solvable_matches(Goal, S),
    solvable_type(S, Type),
    local_solution_of_type(Type, Goal, S, Params, Solution).

%   A data solvable is answered from the store; a procedure solvable by
%   calling its callback, whose backtracking supplies the solutions.
%   Developer's Guide 5.3.

local_solution_of_type(data, Goal, _S, Params, Solution) :-
    copy_term(Goal, Probe),
    (   icl_get_param_value(owner(Owner), Params)
    ->  oaa_data_query(Probe, Owner)
    ;   oaa_data_query(Probe)
    ),
    Solution = Probe.
local_solution_of_type(procedure, Goal, S, Params, Solution) :-
    solvable_callback(S, Callback),
    copy_term(Goal, Probe),
    call(Callback, Probe, Params),
    Solution = Probe.
local_solution_of_type(trigger, _Goal, _S, _Params, _Solution) :-
    %  Trigger solvables are not directly callable: other agents use them by
    %  installing task triggers.  Developer's Guide 4.3.1.
    fail.

apply_solution_limit(Solutions, Params, Limited) :-
    (   icl_get_param_value(solution_limit(N), Params),
        integer(N)
    ->  first_n(N, Solutions, Limited)
    ;   Limited = Solutions
    ).

first_n(N, _, []) :- N =< 0, !.
first_n(_, [], []) :- !.
first_n(N, [H|T], [H|R]) :-
    N1 is N - 1,
    first_n(N1, T, R).

% ---------------------------------------------------------- maintaining data

%!  oaa_add_data(+Clause, +Params) is det.
%!  oaa_remove_data(+Clause, +Params) is det.
%!  oaa_replace_data(+Clause1, +Clause2, +Params) is det.
%
%   Routing follows the same rule as oaa_Solve: with an address parameter the
%   operation goes to the named agents, and without one the facilitator treats
%   the clause as a goal and selects every agent providing a matching data
%   solvable.

oaa_add_data(Clause, Params) :-
    data_op(add, Clause, Clause, Params).

oaa_remove_data(Clause, Params) :-
    data_op(remove, Clause, Clause, Params).

oaa_replace_data(Clause1, Clause2, Params) :-
    data_op(replace, Clause1, replace(Clause1, Clause2), Params).

data_op(Mode, _Probe, Payload, Params) :-
    icl_get_param_value(address(Addr), Params, '$none'),
    (   Addr == self
    ->  apply_data_op_locally(Mode, Payload, Params, _)
    ;   oaa_next_goal_id(GoalId),
        wire_params(Params, WireParams),
        send_to_parent(ev_update_data(GoalId, Mode, Payload, WireParams)),
        icl_get_param_value(reply(Reply), Params, true),
        (   Reply == none
        ->  true
        ;   ( oaa_wait_for(ev_data_updated(GoalId, Requestees, Satisfiers), 10, _)
            ->  bind_return_param(get_address(Requestees), Params),
                bind_return_param(get_satisfiers(Satisfiers), Params)
            ;   true
            )
        )
    ).

%!  apply_data_op_locally(+Mode, +Payload, +Params, -Ok) is det.
%
%   Perform a data maintenance operation on this agent's own store, after
%   checking that a writable data solvable actually covers the clause.  An
%   agent named in an address parameter that does not provide the appropriate
%   data solvable is simply unaffected.

apply_data_op_locally(add, Clause, Params, Ok) :-
    (   writable_data_solvable(Clause, S)
    ->  merged_params(S, Params, P2),
        owner_of(Params, Owner),
        oaa_data_add(Owner, Clause, P2, Ok),
        note_change(Ok, add, Clause)
    ;   Ok = false
    ).
apply_data_op_locally(remove, Clause, Params, Ok) :-
    (   writable_data_solvable(Clause, _)
    ->  owner_of(Params, Owner),
        oaa_data_remove(Owner, Clause, Params, Count),
        ( Count > 0 -> Ok = true ; Ok = false ),
        note_change(Ok, remove, Clause)
    ;   Ok = false
    ).
apply_data_op_locally(replace, replace(C1, C2), Params, Ok) :-
    (   writable_data_solvable(C1, _),
        writable_data_solvable(C2, S2)
    ->  merged_params(S2, Params, P2),
        owner_of(Params, Owner),
        oaa_data_replace(Owner, C1, C2, P2, Ok),
        note_change(Ok, replace(C1, C2), C1)
    ;   Ok = false
    ).

%   A call to any of the data maintenance procedures causes the agent that
%   provides the solvable to check its active data triggers, and may result in
%   one or more of them firing.  Developer's Guide 7.

note_change(true, Operation, Clause) :- !,
    oaa_note_data_change(Operation, Clause).
note_change(_, _, _).

writable_data_solvable(Clause, S) :-
    my_solvable(S),
    solvable_type(S, data),
    solvable_permission(S, write(true)),
    S = solvable(Template, _, _),
    icl_matches(Clause, Template),
    !.

%   Constraints declared on the solvable -- single_value, unique_values --
%   apply to every write, so they are merged in beneath the caller's
%   parameters.

merged_params(S, Params, Merged) :-
    findall(P,
            ( member(Name, [single_value, unique_values]),
              Probe =.. [Name, V],
              solvable_param(S, Probe),
              P =.. [Name, V] ),
            Declared),
    icl_param_apply_defaults(Declared, Params, Merged).

owner_of(Params, Owner) :-
    (   icl_get_param_value(from(From), Params)
    ->  Owner = From
    ;   Owner = self
    ).

% ------------------------------------------------------------ event handling

%!  oaa_handle_event(+ConnId, +Event) is det.
%
%   The agent library's side of the event loop.  Builtin events are handled
%   here, so an agent developer never sees them; anything else goes to the
%   app_do_event callback, as the Developer's Guide describes.

oaa_handle_event(ConnId, Event) :-
    %  Every incoming event is offered to the comm triggers before it is
    %  handled, which is what lets a trigger watch traffic it does not own.
    oaa_note_event(receive, ConnId, Event),
    fail.
oaa_handle_event(ConnId, ev_solve(GoalId, Goal, Params)) :- !,
    solve_for_requester(ConnId, GoalId, Goal, Params).
oaa_handle_event(_ConnId, ev_update_data(GoalId, Mode, Payload, Params)) :- !,
    apply_data_op_locally(Mode, Payload, Params, Ok),
    (   icl_get_param_value(reply(none), Params)
    ->  true
    ;   send_to_parent(ev_data_applied(GoalId, Ok))
    ).
oaa_handle_event(_ConnId, ev_registered(LocalId, _Address)) :- !,
    retractall(my_local_id(_)),
    assertz(my_local_id(LocalId)).
oaa_handle_event(_ConnId, Event) :-
    (   oaa_callback(app_do_event, Closure)
    ->  ignore(call(Closure, Event, []))
    ;   true
    ).

%   Answer a delegated request.  All solutions are gathered before replying,
%   which is the default; delaying them is a separate mechanism.

solve_for_requester(ConnId, GoalId, Goal, Params) :-
    findall(Solution, local_solution(Goal, Params, Solution), Solutions0),
    apply_solution_limit(Solutions0, Params, Solutions),
    (   icl_get_param_value(reply(none), Params)
    ->  true
    ;   reply_goal(Goal, Params, ReplyGoal),
        com_send(ConnId,
                 ev_solved(GoalId, [], [], ReplyGoal, Params, Solutions))
    ).

%   Message bloat: from OAA 2.3.2 the goal is not repeated in the reply; a
%   variable stands in that position.  return_goal_with_solutions restores the
%   old behaviour for a legacy agent that needs it.

reply_goal(Goal, Params, ReplyGoal) :-
    (   icl_get_param_value(return_goal_with_solutions(true), Params)
    ->  ReplyGoal = Goal
    ;   true            % leave ReplyGoal unbound
    ).
